In [75]:
import numpy as np

In [76]:
a = np.arange(300).reshape(10, 10, 3)
a

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29]],

       [[ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44],
        [ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59]],

       [[ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 

In [77]:
a = a.reshape(-1, 3)
a

array([[  0,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11],
       [ 12,  13,  14],
       [ 15,  16,  17],
       [ 18,  19,  20],
       [ 21,  22,  23],
       [ 24,  25,  26],
       [ 27,  28,  29],
       [ 30,  31,  32],
       [ 33,  34,  35],
       [ 36,  37,  38],
       [ 39,  40,  41],
       [ 42,  43,  44],
       [ 45,  46,  47],
       [ 48,  49,  50],
       [ 51,  52,  53],
       [ 54,  55,  56],
       [ 57,  58,  59],
       [ 60,  61,  62],
       [ 63,  64,  65],
       [ 66,  67,  68],
       [ 69,  70,  71],
       [ 72,  73,  74],
       [ 75,  76,  77],
       [ 78,  79,  80],
       [ 81,  82,  83],
       [ 84,  85,  86],
       [ 87,  88,  89],
       [ 90,  91,  92],
       [ 93,  94,  95],
       [ 96,  97,  98],
       [ 99, 100, 101],
       [102, 103, 104],
       [105, 106, 107],
       [108, 109, 110],
       [111, 112, 113],
       [114, 115, 116],
       [117, 118, 119],
       [120, 121, 122],
       [123, 124

In [78]:
A = np.arange(0, 300, 1).reshape(10, 10, 3)
B = A.reshape(-1, 3)
B

array([[  0,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11],
       [ 12,  13,  14],
       [ 15,  16,  17],
       [ 18,  19,  20],
       [ 21,  22,  23],
       [ 24,  25,  26],
       [ 27,  28,  29],
       [ 30,  31,  32],
       [ 33,  34,  35],
       [ 36,  37,  38],
       [ 39,  40,  41],
       [ 42,  43,  44],
       [ 45,  46,  47],
       [ 48,  49,  50],
       [ 51,  52,  53],
       [ 54,  55,  56],
       [ 57,  58,  59],
       [ 60,  61,  62],
       [ 63,  64,  65],
       [ 66,  67,  68],
       [ 69,  70,  71],
       [ 72,  73,  74],
       [ 75,  76,  77],
       [ 78,  79,  80],
       [ 81,  82,  83],
       [ 84,  85,  86],
       [ 87,  88,  89],
       [ 90,  91,  92],
       [ 93,  94,  95],
       [ 96,  97,  98],
       [ 99, 100, 101],
       [102, 103, 104],
       [105, 106, 107],
       [108, 109, 110],
       [111, 112, 113],
       [114, 115, 116],
       [117, 118, 119],
       [120, 121, 122],
       [123, 124

In [79]:
a = np.array([0, 1, 2])
b = np.array([2, 0, 6])
c = np.array([3, 7, 4])
np.maximum(a,b,c)

array([2, 1, 6])

In [80]:
x = np.arange(5, 10, 1)
y = np.arange(5)
print(x)
print(y)
np.divide(x, y, where=(y != 0))

[5 6 7 8 9]
[0 1 2 3 4]


array([0.        , 6.        , 3.5       , 2.66666667, 2.25      ])

In [81]:
100 * x

array([500, 600, 700, 800, 900])

In [82]:
h1 = np.arange(5)
h2 = np.arange(5)
print(h1, h2)
np.mean([h1,h2], axis=0)

[0 1 2 3 4] [0 1 2 3 4]


array([0., 1., 2., 3., 4.])

In [83]:
for i in range(3):
    for j in range(3):
        print(i, j)

0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2


In [84]:
a = np.empty((2, 4))
a

array([[1.30625344e-316, 0.00000000e+000, 3.53522910e-033,
        1.05235781e-153],
       [9.45893095e-154, 7.22937895e+159, 1.23755836e+214,
        4.44387685e+252]])

In [85]:
a[1, :]

array([9.45893095e-154, 7.22937895e+159, 1.23755836e+214, 4.44387685e+252])

In [86]:
a = np.arange(10).reshape((2, 5))
a.ndim

2

In [87]:
a = np.arange(10).reshape((1, 10))
a.ndim

2

In [88]:
norm = (a ** 2).sum(1, keepdims=True) ** .5
norm

array([[16.88194302]])

In [118]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([1, 2, 3])
print(np.dot(x, y))
x_norm = (x ** 2).sum(axis=1, keepdims=True) ** .5
y_norm = (y ** 2).sum(axis=0, keepdims=True) ** .5
print(x_norm)
print(y_norm)
np.dot(x, y) / x_norm.T / y_norm

[14 32]
[[3.74165739]
 [8.77496439]]
[3.74165739]


array([[1.        , 0.97463185]])